name: 'Test Report'

on:
  workflow_run:
    workflows: ['Execute tests']
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: Test Results
          path: '**/TEST-*.xml'
          reporter: java-junit